name: Deployment

on:
  push:
    branches:
      - master
      - master-release
    paths-ignore:
      - 'docs/**'
      - 'src/test/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'src/test/**'
      - 'README.md'

env:
  SpringerNatureAPIKey: ${{ secrets.SpringerNatureAPIKey }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]
        include:
          - os: macOS-latest
            displayName: macOS
            archivePortable: brew install pigz && tar -c -C build/distribution JabRef.app | pigz --rsyncable > build/distribution/JabRef-portable_macos.tar.gz && rm -R build/distribution/JabRef.app

    runs-on: ${{ matrix.os }}
    name: Create installer and portable version for ${{ matrix.displayName }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.2
        with:
          versionSpec: '5.2.x'
#      - name: Run GitVersion
#        id: gitversion
#        uses: gittools/actions/gitversion/execute@v0.9.2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build runtime image
        run: ./gradlew -is -PprojVersion="${{ steps.gitversion.outputs.AssemblySemVer }}" -PprojVersionInfo="${{ steps.gitversion.outputs.InformationalVersion }}" jlinkZip
      - name: Build installer
        run: ./gradlew -is -PprojVersion="${{ steps.gitversion.outputs.AssemblySemVer }}" -PprojVersionInfo="${{ steps.gitversion.outputs.InformationalVersion }}" jpackage
        shell: bash
      - name: Package application image
        run: ${{ matrix.archivePortable }}
        shell: bash
      - name: Rename files
        run: |
          get-childitem -Path build/distribution/*
          get-childitem -Path build/distribution/* | rename-item -NewName {$_.name -replace "${{ steps.gitversion.outputs.AssemblySemVer }}","${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor }}"}
          get-childitem -Path build/distribution/* | rename-item -NewName {$_.name -replace "portable","${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor }}-portable"}
        shell: pwsh
      - name: Upload to GitHub workflow artifacts store
        uses: actions/upload-artifact@master
        with:
          name: JabRef-${{ matrix.displayName }}
          path: build/distribution
